#!/bin/bash

# Update nginx configuration to run as nginx user
sed -i 's/user\s*nginx;/user nginx nginx;/' /etc/nginx/nginx.conf

# Restart nginx service
service nginx restart

# Verify nginx is running as nginx user
ps auxff | grep ngin[x]

# Verify nginx is listening on port 8080
nc -z 0 8080
